version: '3.8'

services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey-cache
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    command: valkey-server --appendonly yes
    restart: unless-stopped
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inkhub-admin
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=valkey
      - REDIS_PORT=6379
    depends_on:
      - valkey
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  valkey-data:
    driver: local 